"""
Multi-agent pipeline — Generated by AgentVoy
Agents run sequentially, each building on the previous stage's output.

Stages: researcher → writer → reviewer
"""
from agentvoy_guard import Guard

from src.agents.researcher import run_agent as researcher_agent
from src.agents.writer import run_agent as writer_agent
from src.agents.reviewer import run_agent as reviewer_agent

guard = Guard.from_config()


def run_pipeline(prompt: str) -> dict:
    """Run all agents in sequence and return the final result."""
    with guard.session() as session:
        session.check_input(prompt)

        # Stage 1: researcher
        researcher_result = researcher_agent(prompt)
        session.tick()

        # Stage 2: writer
        writer_result = writer_agent(researcher_result)
        session.tick()

        # Stage 3: reviewer
        reviewer_result = reviewer_agent(writer_result)
        session.tick()

        session.check_output(str(reviewer_result))

    return {
        "result": reviewer_result,
        "stages": ["researcher", "writer", "reviewer"],
        "guard_summary": guard.last_summary,
    }


if __name__ == "__main__":
    import sys
    user_prompt = " ".join(sys.argv[1:]) or "Hello! What can you help me with?"
    result = run_pipeline(user_prompt)
    print(result["result"])
