"""
API server — Generated by AgentVoy
Wraps your agent as a FastAPI endpoint with agent.guard.yml enforcement.

Run:
    uvicorn server:app --reload --port 8080

Endpoints:
    POST /run    — send a prompt, get a response
    GET  /health — health check
"""
import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

from src.pipeline import run_pipeline

app = FastAPI(
    title="demo-app",
    description="AI agent powered by AgentVoy",
    version="0.1.0",
)


class AgentRequest(BaseModel):
    prompt: str
    session_id: str | None = None


class AgentResponse(BaseModel):
    response: str
    guard_summary: dict | None = None


@app.post("/run")
async def run(request: AgentRequest) -> AgentResponse:
    try:
        result = run_pipeline(request.prompt)
        response = str(result["result"]) if isinstance(result, dict) else str(result)
        guard_summary = result.get("guard_summary") if isinstance(result, dict) else None
        return AgentResponse(response=response, guard_summary=guard_summary)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
async def health():
    return {"status": "ok", "agent": "demo-app"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
