"""
Chat UI — Generated by AgentVoy
Streamlit app that talks to the FastAPI server.

Run (with server already running on port 8080):
    streamlit run streamlit_app.py
"""
import streamlit as st
import requests

API_URL = "http://localhost:8080"

st.set_page_config(
    page_title="demo-app",
    page_icon="🤖",
    layout="centered",
)
st.title("demo-app")
st.caption("Powered by AgentVoy")

with st.sidebar:
    st.subheader("Pipeline")
    for stage in ["researcher", "writer", "reviewer"]:
        st.write(f"• {stage}")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

if prompt := st.chat_input("Ask your agent..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                resp = requests.post(
                    f"{API_URL}/run",
                    json={"prompt": prompt},
                    timeout=120,
                )
                resp.raise_for_status()
                data = resp.json()
                st.write(data["response"])

                if data.get("stages"):
                    with st.expander("Pipeline stages", expanded=False):
                        for stage in data["stages"]:
                            st.write(f"\u2713 {stage}")

                if data.get("guard_summary"):
                    with st.sidebar:
                        st.subheader("Guard summary")
                        st.json(data["guard_summary"])

            except requests.exceptions.ConnectionError:
                st.error(f"Cannot connect to agent server at {API_URL}. Is it running?")
                st.code(f"uvicorn server:app --port 8080")
                data = {"response": ""}
            except Exception as e:
                st.error(f"Error: {e}")
                data = {"response": ""}

    if data.get("response"):
        st.session_state.messages.append({"role": "assistant", "content": data["response"]})
